
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-mirrors-kts-studio-v1alpha2-secretmirror
  failurePolicy: Fail
  name: msecretmirror.kb.io
  rules:
  - apiGroups:
    - mirrors.kts.studio
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - secretmirrors
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-mirrors-kts-studio-v1alpha2-secretmirror
  failurePolicy: Fail
  name: vsecretmirror.kb.io
  rules:
  - apiGroups:
    - mirrors.kts.studio
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - secretmirrors
  sideEffects: None
