apiVersion: v1
stringData:
  token: YOURTOKEN
kind: Secret
metadata:
  name: vault-token
  namespace: default
type: Opaque
---
apiVersion: mirrors.kts.studio/v1alpha2
kind: SecretMirror
metadata:
  name: secretmirror-from-vault-to-vault
  namespace: default
spec:
  source:
    name: mysecret
    type: vault
    vault:
      addr: https://vault.example.com
      path: /secret/data/mysecret
      auth:
        approle:
          secretRef:
            name: vault-approle

  destination:
    type: vault
    vault:
      addr: https://vault.example.com
      path: /secret/data/mysecret2
      auth:
        approle:
          secretRef:
            name: vault-approle



