apiVersion: v1
stringData:
  token: YOURTOKEN
kind: Secret
metadata:
  name: vault-token
  namespace: default
type: Opaque
---
apiVersion: mirrors.kts.studio/v1alpha2
kind: SecretMirror
metadata:
  name: secretmirror-vault-token
  namespace: default
spec:
  source:
    name: mysecret
  destination:
    type: vault
    vault:
      addr: https://vault.example.com
      path: /secret/data/mysecret
      auth:
        token:
          secretRef:
            name: vault-token

