apiVersion: v1
stringData:
  role-id: ROLEID
  secret-id: SECRETID
kind: Secret
metadata:
  name: vault-approle
  namespace: default
type: Opaque
---
apiVersion: mirrors.kts.studio/v1alpha2
kind: SecretMirror
metadata:
  name: secretmirror-vault-approle
  namespace: default
spec:
  source:
    name: mysecret
  destination:
    type: vault
    vault:
      addr: https://vault.example.com
      path: /secret/data/mysecret-via-approle
      auth:
        approle:
          secretRef:
            name: vault-approle
