apiVersion: mirrors.kts.studio/v1alpha2
kind: SecretMirror
metadata:
  name: secretmirror-normal
  namespace: default
spec:
  deletePolicy: retain
  source:
    name: mysecret
  destination:
    namespaces:
      - testns\d+
      - testanotherns\d+
